### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by Borda**
drop missing function ExecuteInverse since it was removed in https://github.com/SuperElastix/SimpleElastix/commit/1678d41cfb9ca5fd3a46583926a9a76abcbff628

TODO, it would be nice to add how to get the warped points... :)

@kaspermarstal , what do you think?

### CODE REVIEW

**Comment by Borda** [comment]
@mstaring, what do you think? :)

**Comment by Borda** [comment]
@mstaring @kaspermarstal could you pls have a look at this edit... :)

**Comment by mstaring** [comment]
@kaspermarstal can you confirm?

**Comment by Borda** [comment]
@kaspermarstal ^^

**Comment by Borda** [comment]
any update here? @mstaring @kaspermarstal

**Comment by Borda** [comment]
any update here? @mstaring @kaspermarstal

**Comment by mstaring** [comment]
@kaspermarstal could you have a look at the edit and merge it ?

**Comment by Borda** [comment]
@mstaring @kaspermarstal ^^

**Comment by Borda** [comment]
@mstaring @kaspermarstal ^^

**Comment by Borda** [comment]
@mstaring @kaspermarstal ^^

**Comment by Borda** [comment]
@mstaring @blowekamp @blezek @gabehart @dave3d who else can merge it? :)

**Comment by kaspermarstal** [comment]
Oops, sorry to leave you hanging. Thanks!!

**Pull request merged**
